apiVersion: apps/v1
kind: Deployment
metadata:
  name: learningsteps-api
  labels:
    app: learningsteps-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learningsteps-api
  template:
    metadata:
      labels:
        app: learningsteps-api
    spec:
      containers:
        - name: api
          image: acrlearningstepslokiyna78be3.azurecr.io/learningsteps-api:v1
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: learningsteps-config
                  key: ENVIRONMENT
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: learningsteps-db
                  key: db-password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: learningsteps-db
                  key: db-host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: learningsteps-db
                  key: db-name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: learningsteps-db
                  key: db-user
            - name: DATABASE_URL
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):5432/$(DB_NAME)?sslmode=require"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: kv-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: learningsteps-kv
