apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: learningsteps-kv
spec:
  provider: azure
  secretObjects:
    - secretName: learningsteps-db
      type: Opaque
      data:
        - objectName: db-password
          key: db-password
        - objectName: db-host
          key: db-host
        - objectName: db-name
          key: db-name
        - objectName: db-user
          key: db-user
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "30e19114-e57d-4c85-9c46-36bf91473cd8"
    keyvaultName: "kv-ls-lokiyna78be3"
    tenantId: "c0531484-50fa-4ff2-97df-b1f2d4810603"
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: db-host
          objectType: secret
        - |
          objectName: db-name
          objectType: secret
        - |
          objectName: db-user
          objectType: secret
